// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbG75zRLNqrFdGAFevKuqXeKtgNvtZyT4',
    appId: '1:284917958060:web:2e8b2e528614faa2dc2609',
    messagingSenderId: '284917958060',
    projectId: 'student-career-app-b8d0a',
    authDomain: 'student-career-app-b8d0a.firebaseapp.com',
    storageBucket: 'student-career-app-b8d0a.firebasestorage.app',
    measurementId: 'G-RYW6D2X7MH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjnLMQbyVvkGgCKyeZ18pvAt0gmaoPxAk',
    appId: '1:284917958060:android:4fa2ae7bbf81dac9dc2609',
    messagingSenderId: '284917958060',
    projectId: 'student-career-app-b8d0a',
    storageBucket: 'student-career-app-b8d0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxwBUtLkhmf8MwG4e3G9pjqEuywR8a_wU',
    appId: '1:284917958060:ios:41ec7795de98930cdc2609',
    messagingSenderId: '284917958060',
    projectId: 'student-career-app-b8d0a',
    storageBucket: 'student-career-app-b8d0a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxwBUtLkhmf8MwG4e3G9pjqEuywR8a_wU',
    appId: '1:284917958060:ios:41ec7795de98930cdc2609',
    messagingSenderId: '284917958060',
    projectId: 'student-career-app-b8d0a',
    storageBucket: 'student-career-app-b8d0a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbG75zRLNqrFdGAFevKuqXeKtgNvtZyT4',
    appId: '1:284917958060:web:39756433ff1b167ddc2609',
    messagingSenderId: '284917958060',
    projectId: 'student-career-app-b8d0a',
    authDomain: 'student-career-app-b8d0a.firebaseapp.com',
    storageBucket: 'student-career-app-b8d0a.firebasestorage.app',
    measurementId: 'G-VV2NTRKLMC',
  );

}